### ISSUE TITLE
Building a NER training / evaluation corpus from Wikipedia and DBpedia

### ISSUE THREAD

**Issue by tilneyyang** [dbpedia-spotlight/pignlproc#15]
I am trying to generate ner training data, everything works fine with the example data.
But something's wrong with newer data.

``` java
Data : ruwiki-20141114-pages-articles-multistream.xml
Script: example/extract_links.pig
Exception: 

2014-12-09 12:18:13,650 [Thread-490] WARN  org.apache.hadoop.mapred.FileOutputCommitter - Output path is null in cleanup
2014-12-09 12:18:13,651 [Thread-490] WARN  org.apache.hadoop.mapred.LocalJobRunner - job_local_0003
java.io.IOException: Illegal partition for Null: false index: 0 (http://ru.wikipedia.org/wiki/2006,Список астероидов (178001—178100),1) (13)
    at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.collect(MapTask.java:1073)
    at org.apache.hadoop.mapred.MapTask$NewOutputCollector.write(MapTask.java:691)
    at org.apache.hadoop.mapreduce.TaskInputOutputContext.write(TaskInputOutputContext.java:80)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapReduce$Map.collect(PigGenericMapReduce.java:128)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapBase.runPipeline(PigGenericMapBase.java:273)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapBase.map(PigGenericMapBase.java:266)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapBase.map(PigGenericMapBase.java:64)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:144)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:370)
    at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:212)
2014-12-09 12:18:16,993 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - job job_local_0003 has failed! Stop running all dependent jobs
```

**Comment by tilneyyang** [comment]
It could be a hadoop version problem. I tried again with hadoop 0.20.2 and pig1.10.0. Everything works fine.

[More info](https://github.com/ogrisel/pignlproc/issues/7) could be found here.
